# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mokapi < Formula
  desc "Your API Mocking Tool for Agile Development using Go and Javascript - https://mokapi.io"
  homepage "https://mokapi.io"
  version "0.17.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marle3003/mokapi/releases/download/v0.17.1/mokapi_v0.17.1_darwin_amd64.tar.gz"
      sha256 "70bcf7e179e7f01f3cce13985be39f157ba9093cb819e42c41fef5d7437c5be4"

      def install
        bin.install "mokapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marle3003/mokapi/releases/download/v0.17.1/mokapi_v0.17.1_darwin_arm64.tar.gz"
      sha256 "52d1b0feb20340f38495c8405a61d69f80b05a4756476501cd8537c98502c4b3"

      def install
        bin.install "mokapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marle3003/mokapi/releases/download/v0.17.1/mokapi_v0.17.1_linux_amd64.tar.gz"
      sha256 "5821b0829d6af08fda34205565212268e510020d3430a0b15102615469a447b5"
      def install
        bin.install "mokapi"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marle3003/mokapi/releases/download/v0.17.1/mokapi_v0.17.1_linux_arm64.tar.gz"
      sha256 "4ec1cb0e56ba75dd35aff4efd73b010c3bddca0a6e341b0991dc0c4ea42db4de"
      def install
        bin.install "mokapi"
      end
    end
  end
end
