# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mokapi < Formula
  desc "Your API Mocking Tool for Agile Development using Go and Javascript - https://mokapi.io"
  homepage "https://mokapi.io"
  version "0.11.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marle3003/mokapi/releases/download/v0.11.8/mokapi_v0.11.8_darwin_amd64.tar.gz"
      sha256 "d9b809f22e9d1a772c31d86062721d41c7c9602de19d0acf13f2d79424e2f342"

      def install
        bin.install "mokapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marle3003/mokapi/releases/download/v0.11.8/mokapi_v0.11.8_darwin_arm64.tar.gz"
      sha256 "c997be63d40bf56232ca1e486906ab1146f13dea24662597dc804a3a03c74028"

      def install
        bin.install "mokapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marle3003/mokapi/releases/download/v0.11.8/mokapi_v0.11.8_linux_amd64.tar.gz"
        sha256 "9d91b9a573750e2437a9daa295a59ea7b9ef41174e5e0dd6faa3eafc69a78649"

        def install
          bin.install "mokapi"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marle3003/mokapi/releases/download/v0.11.8/mokapi_v0.11.8_linux_arm64.tar.gz"
        sha256 "6e99ea54a8ae3b319ba26ca38ecbac38910d3632cdbb2c64e73e4a9d4656720f"

        def install
          bin.install "mokapi"
        end
      end
    end
  end
end
