# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mokapi < Formula
  desc "Your API Mocking Tool for Agile Development using Go and Javascript - https://mokapi.io"
  homepage "https://mokapi.io"
  version "0.12.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marle3003/mokapi/releases/download/v0.12.0/mokapi_v0.12.0_darwin_amd64.tar.gz"
      sha256 "bf1d0548368c317b35a638907e799a9569b3c3684951466387f6e5f66dc8fdf0"

      def install
        bin.install "mokapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marle3003/mokapi/releases/download/v0.12.0/mokapi_v0.12.0_darwin_arm64.tar.gz"
      sha256 "e40261755cd9b6207a662ac2777ed259f9badb22ffa77bf8929c45780395af78"

      def install
        bin.install "mokapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marle3003/mokapi/releases/download/v0.12.0/mokapi_v0.12.0_linux_amd64.tar.gz"
        sha256 "11e573d365466d6a4efcaf94cfe2fcb2b27356603b9408b8853aa0cf00ebe610"

        def install
          bin.install "mokapi"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marle3003/mokapi/releases/download/v0.12.0/mokapi_v0.12.0_linux_arm64.tar.gz"
        sha256 "26f489daee94343b891dc2ac48db8c2abd6b10d2b381182ec666ecbe8fa0d837"

        def install
          bin.install "mokapi"
        end
      end
    end
  end
end
